CREATE SEQUENCE jogging_seq START WITH 100;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 100;

CREATE TABLE IF NOT EXISTS JOGGING_USER(id INT PRIMARY KEY, login VARCHAR(255), password VARCHAR(80));

CREATE TABLE IF NOT EXISTS JOGGING_RACE(id INT PRIMARY KEY, distance NUMBER (255),
date TIMESTAMP, duration BIGINT, user_id INT,
FOREIGN KEY(user_id) REFERENCES PUBLIC.JOGGING_USER(id));